# Site settings
title: Rúben André Barreiro
email: ruben.barreiro.92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A web-based portfolio/personal blog designed and developed to illustrate some of hard skills,
  soft skills, competences, hobbies, important documents, among many others.
  Here will be shown some of my academic, professional and personal works, as some of my photography and
  modeling photoshoot's works, among many others.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ruben_badnewz
github_username: rubenandrebarreiro
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: true
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
